# Generated by Django 5.0.3 on 2025-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.IntegerField(blank=True, null=True)),
                ("vin", models.CharField(blank=True, max_length=17, null=True)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
    ]
